#include <msp430.h>

#define CLK_DEBUG_PORT_SEL	P11SEL
#define CLK_DEBUG_PORT_DIR 	P11DIR

#define ACLK_DBG_PIN	BIT0
#define MCLK_DBG_PIN	BIT1
#define SMCLK_DBG_PIN	BIT2

#define ENABLE_SMCLK_DBG() P11DIR |= SMCLK_DBG_PIN; P11SEL |= SMCLK_DBG_PIN;
#define ENABLE_MCLK_DBG() P11DIR |= MCLK_DBG_PIN; P11SEL |= MCLK_DBG_PIN;
#define ENABLE_ACLK_DBG() P11DIR |= ACLK_DBG_PIN; P11SEL |= ACLK_DBG_PIN;


#define ENABLE_CLK_DBG() \
	ENABLE_SMCLK_DBG()	\
	ENABLE_MCLK_DBG()	\
	ENABLE_ACLK_DBG()

