#ifndef HCI_CMDS_H_

#define HCI_CMDS_H_
#include <msp430.h>
#include <stdint.h>


#define OGF_HCI_LINK_CONTROL 				0x01

#define OCF_INQ								0x0001
#define OCF_INQ_CANCEL						0x0002
#define OCF_PERIODIC_INQ_MODE				0x0003
#define OCF_EXIT_PERIODIC_INQ_MODE			0x0004
#define OCF_CREATE_CONNECTION				0x0005
#define OCF_DISCONNECT						0x0006
#define OCF_CREATE_CONNECTION_CANCEL		0x0008
#define OCF_ACCEPT_CONN_REQ					0x0009
#define OCF_REJECT_CONN_REQ					0x000A
#define OCF_LINK_KEY_REQ_REPLY				0x000B
#define OCF_LINK_KEY_REQ_NEG_REPLY			0x000C
#define OCF_PIN_CODE_REQ_REPLY				0x000D
#define OCF_PIN_CODE_REQ_NEG_REPLY			0x000E
#define OCF_CHANGE_CONN_PACKET_TYPE			0x000F
#define OCF_AUTH_REQ						0x0011
#define OCF_SET_CONN_ENCRYPTION				0x0013
#define OCF_CHANGE_CONN_LINK_KEY			0x0015
#define OCF_MASTER_LINK_KEY					0x0017
#define OCF_REMOTE_NAME_REQ					0x0019
#define OCF_REMOTE_NAME_REQ_CANCEL			0x001A
#define OCF_READ_REMOTE_SUPPORTED_FEATURES 	0x001B
#define OCF_READ_REMOTE_EXTENDED_FEATURES	0x001C
#define OCF_REMOTE_VERSION_INFORMATION		0x001D
#define OCF_READ_CLOCK_OFFSET				0x001F
#define OCF_READ_LMP_HANDLE					0x0020
#define OCF_SETUP_SYNC_CONN					0x0028
#define OCF_ACCEPT_SYNC_CONN_REQ			0x0029
#define OCF_REJECT_SYNC_CONN_REQ			0x002A
#define OCF_IO_CAPABILITY_REQ_REPLY			0x002B
#define OCF_USER_CONFIRM_REQ_REPLY			0x002C
#define OCF_USER_CONFIRM_REQ_NEG_REPLY		0x002D
#define OCF_PASSKEY_REQ_REPLY				0x002E
#define OCF_PASSKEY_REQ_NEG_REPLY			0x002F
#define OCF_REMOTE_OOB_DATA_REQ_REPLY		0x0030
#define OCF_REMOTE_OOB_DATA_REQ_NEG_REPLY	0x0033
#define OCF_IO_CAPABILITY_REQ_NEG_REPLY		0x0034


#define OGF_HCI_LINK_POLICY						0x02

#define OCF_HOLD_MODE							0x0001
#define OCF_SNIFF_MODE							0x0003
#define OCF_EXIT_SNIFF_MODE						0x0004
#define OCF_PARK_STATE							0x0005
#define OCF_EXIT_PARK_STATE						0x0006
#define OCF_QoS_SETUP							0x0007
#define OCF_ROLE_DISCOVERY						0x0009
#define OCF_SWITCH_ROLE							0x000B
#define OCF_READ_LINK_POLICY_SETTINGS			0x000C
#define OCF_WRITE_LINK_POLICY_SETTINGS			0x000D
#define OCF_READ_DEFAULT_LINK_POLICY_SETTINGS	0x000E
#define OCF_WRITE_DEFAULT_LINK_POLICY_SETTINGS	0x000F
#define OCF_FLOW_SPECIFICATION					0x0010
#define OCF_SNIFF_SUBRATING						0x0011

#define OGF_HCI_CONTROLLER_BASEBAND 					0x03

#define OCF_SET_EVENT_MASK								0x0001
#define OCF_RESET										0x0003
#define OCF_SET_EVENT_FILTER							0x0005
#define OCF_FLUSH										0x0008
#define OCF_READ_PIN_TYPE								0x0009
#define OCF_WRITE_PIN_TYPE								0x000A
#define OCF_CREATE_NEW_UNIT_KEY							0x000B
#define OCF_READ_STORED_LINK_KEY						0x000D
#define OCF_WRITE_STORED_LINK_KEY						0x0011
#define OCF_DELETE_STORED_LINK_KEY						0x0012
#define OCF_WRITE_LOCAL_NAME							0x0013
#define OCF_READ_LOCAL_NAME								0x0014
#define OCF_READ_CONNECTION_ACCEPT_TIMEOUT				0x0015
#define OCF_WRITE_CONNECTION_ACCEPT_TIMEOUT				0x0016
#define OCF_READ_PAGE_TIMEOUT							0x0017
#define OCF_WRITE_PAGE_TIMEOUT							0x0018
#define OCF_READ_SCAN_ENABLE							0x0019
#define OCF_WRITE_SCAN_ENABLE							0x001A
#define OCF_READ_PAGE_SCAN_ACTIVITY						0x001B
#define OCF_WRITE_PAGE_SCAN_ACTIVITY					0x001C
#define OCF_READ_INQUIRY_SCAN_ACTIVITY					0x001D
#define OCF_WRITE_INQUIRY_SCAN_ACTIVITY					0x001E
#define OCF_READ_AUTH_ENABLE							0x001F
#define OCF_WRITE_AUTH_ENABLE							0x0020
#define OCF_READ_CLASS_OF_DEVICE						0x0023
#define OCF_WRITE_CLASS_OF_DEVICE						0x0024
#define OCF_READ_VOICE_SETTINGS							0x0025
#define OCF_WRITE_VOICE_SETTINGS						0x0026
#define OCF_READ_AUTOMATIC_FLUSH_TIMEOUT				0x0027
#define OCF_WRITE_AUTOMATIC_FLUSH_TIMEOUT				0x0028
#define OCF_READ_NUM_BROADCAST_RETRANSMISSIONS			0x0029
#define OCF_WRITE_NUM_BROADCAST_RETRANSMISSIONS			0x002A
#define OCF_READ_HOLD_MODE_ACTIVITY						0x002B
#define OCF_WRITE_HOLD_MODE_ACTIVITY					0x002C
#define OCF_READ_TRANSMIT_POWER_LEVEL					0x002D
#define OCF_READ_SYNCH_FLOW_CONTROL						0x002E
#define OCF_WRITE_SYNCH_FLOW_CONTROL					0x002F
#define OCF_SET_CONTROLLER_TO_HOST_FLOW_CONTROL			0x0031
#define OCF_HOST_BUFFER_SIZE							0x0033
#define OCF_HOST_NUM_COMPLETED_PACKETS					0x0035
#define OCF_READ_LINK_SUPERVISION_TIMEOUT				0x0036
#define OCF_WRITE_LINK_SUPERVISION_TIMEOUT				0x0037
#define OCF_READ_NUM_SUPPORTED_IAC						0x0038
#define OCF_READ_CURRENT_IAC_LAP						0x0039
#define OCF_WRITE_CURRENT_IAC_LAP						0x003A
#define OCF_SET_AFH_HOST_CHANNEL_CLASSIFICATION			0x003F
#define OCF_READ_INQUIRY_SCAN_TYPE						0x0042
#define OCF_WRITE_INQUIRY_SCAN_TYPE						0x0043
#define OCF_READ_INQUIRY_MODE							0x0044
#define OCF_WRITE_INQUIRY_MODE							0x0045
#define OCF_READ_PAGE_SCAN_TYPE							0x0046
#define OCF_WRITE_PAGE_SCAN_TYPE						0x0047
#define OCF_READ_AFH_CHANNEL_ASSESSMENT_MODE			0x0048
#define OCF_WRITE_AFH_CHANNEL_ASSESSMENT_MODE			0x0049
#define OCF_READ_EXTENDED_INQUIRY_RESPONSE				0x0051
#define OCF_WRITE_EXTENDED_INQUIRY_RESPONSE				0x0052
#define OCF_REFRESH_ENCRYPTION_KEY						0x0053
#define OCF_READ_SIMPLE_PAIRING_MODE					0x0055
#define OCF_WRITE_SIMPLE_PAIRING_MODE					0x0056
#define OCF_READ_LOCAL_OOB_DATA							0x0057
#define OCF_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL	0x0058
#define OCF_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL			0x0059
#define OCF_SEND_KEYPRESS_NOTIFICATION					0x0060
#define OCF_READ_DEFAULT_ERRONEOUS_DATA_REPORTING		0x005A
#define OCF_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING		0x005B
#define OCF_ENCHANCED_FLUSH								0x005F

#define OGF_HCI_INFO_PARAM 					0x04

#define OCF_READ_LOCAL_VERSION_INFO			0x0001
#define OCF_READ_LOCAL_SUPPORTED_CMDS		0x0002
#define OCF_READ_LOCAL_SUPPORTED_FEATURES	0x0003
#define OCF_READ_LOCAL_EXTENDED_FEATURES	0x0004
#define OCF_READ_BUFFER_SIZE				0x0005
#define OCF_READ_BD_ADDR					0x0009


#define OGF_HCI_STATUS_PARAM				0x05

#define OCF_READ_FAILED_CONTACT_COUNTER		0x0001
#define OCF_RESET_FAILED_CONTACT_COUNTER	0x0002
#define OCF_READ_LINK_QUALITY				0x0003
#define OCF_READ_RSSI						0x0005
#define OCF_READ_AFH_CHANNEL_MAP			0x0006
#define OCF_READ_CLOCK						0x0007

#define OGF_HCI_TESTING				0x06

#define OCF_READ_LOOPBACK_MODE				0x0001
#define OCF_WRITE_LOOPBACK_MODE				0x0002
#define OCF_ENABLE_DUT_MODE					0x0003
#define OCF_WRITE_SIMPLE_PAIRING_DEBUG_MODE	0x0004

#define OGF_TI_VS						0x3F
#define OCF_HCI_VS_START_VS_LOCK		0x237

#define INQUIRY_COMPLETE_EVENT								0x01
#define INQUIRY_RESULT_EVENT								0x02
#define CONNECTION_COMPLETE_EVENT							0x03
#define CONNECTION_REQUEST_EVENT							0x04
#define DISCONNECTION_COMPLETE_EVENT						0x05
#define AUTH_COMPLETE_EVENT									0x06
#define REMOTE_NAME_REQ_COMPLETE_EVENT						0x07
#define ENCRYPTION_CHANGE_EVENT								0x08
#define CHANGE_CONNECTION_LINK_KEY_COMPLETE_EVENT			0x09
#define MASTER_LINK_KEY_COMPLETE_EVENT						0x0A
#define READ_REMOTE_SUPPORTED_FEATURES_COMPLETE_EVENT		0x0B
#define READ_REMOTE_VERSION_INFO_COMPLETE_EVENT				0x0C
#define QoS_SETUP_COMPLETE_EVENT							0x0D
#define COMMAND_COMPLETE_EVENT								0x0E
#define COMMAND_STATUS_EVENT								0x0F
#define HW_ERROR_EVENT										0x10
#define FLUSH_OCCURRED_EVENT 								0x11
#define ROLE_CHANGE_EVENT									0x12
#define NUM_OF_COMPLETED_PACKETS_EVENT						0x13
#define MODE_CHANGE_EVENT									0x14
#define RETURN_LINK_KEYS_EVENT								0x15
#define PIN_CODE_REQUEST_EVENT								0x16
#define LINK_KEY_REQUEST_EVENT								0x17
#define LINK_KEY_NOTIFICATION_EVENT							0x18
#define LOOPBACK_COMMAND_EVENT								0x19
#define DATA_BUFFER_OVERFLOW_EVENT							0x1A
#define MAX_SLOTS_CHANGE_EVENT								0x1B
#define READ_CLOCK_OFFSET_COMPLETE_EVENT					0x1C
#define CONNECTION_PACKET_TYPE_CHANGED_EVENT				0x1D
#define QoS_VIOLATION_EVENT									0x1E
#define PAGE_SCAN_REPETITION_MODE_CHANGE_EVENT				0x20
#define FLOW_SPECIFICATION_COMPLETE_EVENT					0x21
#define INQUIRY_RESULT_WITH_RSSI_EVENT						0x22
#define READ_REMOTE_EXTENDED_FEATURES_COMPLETE_EVENT		0x23
#define SYNCH_CONN_COMPLETE_EVENT							0x2C
#define SYNCH_CONN_CHANGED_EVENT							0x2D
#define SNIFF_SUBRATING_EVENT								0x2E
#define EXTENDED_INQUIRY_RESULT_EVENT						0x2F
#define ENCRYPTION_KEY_REFRESH_COMPLETE_EVENT				0x30
#define IO_CAPABILITY_REQUEST_EVENT							0x31
#define IO_CAPABILITY_RESPONSE_EVENT						0x32
#define USER_CONFIRMATION_REQUEST_EVENT						0x33
#define USER_PASSKEY_REQUEST_EVENT							0x34
#define REMOTE_OOB_DATA_REQUEST_EVENT						0x35
#define SIMPLE_PAIRING_COMPLETE_EVENT						0x36
#define LINK_SUPERVISION_TIMEOUT_CHANGED_EVENT				0x38
#define ENHANCED_FLUSH_COMPLETE_EVENT						0x39
#define USER_PASSKEY_NOTIFICATION_EVENT						0x3B
#define KEYPRESS_NOTIFICATION_EVENT							0x3C
#define REMOTE_HOST_SUPPORTED_FEATURES_NOTIFICATION_EVENT 	0x3D

/* Error codes */
#define HCI_CMD_SUCCESS								0x00
#define UNKNOWN_HCI_COMMAND							0x01
#define UNKNOWN_CONNECTION_IDENTIFIER				0x02
#define HARDWARE_FAILURE							0x03
#define PAGE_TIMEOUT								0x04
#define AUTH_FAILURE								0x05
#define PIN_KEY_MISSING								0x06
#define MEMORY_CAPACITY_EXCEEDED					0x07
#define CONNECTION_TIMEOUT							0x08
#define CONNECTION_LIMIT_EXCEEDED					0x09
#define SYNCH_CONNECTION_LIMIT_TO_DEVICE_EXCEEDED	0x0A
#define ACL_CONN_EXISTS								0x0B
#define COMMAND_DISALLOWED							0x0C
#define CONN_REJECTED_LIMITED_RESOURCES				0x0D
#define CONN_REJECTED_SECURITY_REASONS				0x0E
#define CONN_REJECTED_UNACCEPTABLE_BDADDR			0x0F
#define CONN_ACCEPT_TIMEOUT_EXCEEDED				0x10
#define UNSUPPORTED_FEATURE_PARAM_VALUE				0x11
#define INVALID_HCI_CMD_PARAM						0x12
#define REMOTE_USER_TERMINATED_CONN					0x13
#define REMOTE_DEV_TERMINATE_CONN_LOW_RESOURCES		0x14
#define REMOTE_DEV_TERMINATE_CONN_PWR_OFF			0x15
#define CONN_TERMINATED_LOCALHOST					0x16
#define REPEATED_ATTEMPTS							0x17
#define PAIRING_NOT_ALLOWED							0x18
#define UNKOWN_LMP_PDU								0x19
#define UNSUPPORTED_REMOTE_LMP_FEATURE				0x1A
#define SCO_OFFSET_REJECTED							0x1B
#define SCO_INTERVAL_REJECTED						0x1C
#define SCO_AIR_MODE_REJECTED						0x1D
#define INVALID_LMP_PARAM							0x1E
#define UNSPECIFIED_ERROR							0x1F
#define UNSUPPORTED_LMP_PARAM_VALUE					0x20
#define ROLE_CHANGE_NOT_ALLOWED						0x21
#define LMP_RESPONSE_TIMEOUT						0x22
#define LMP_ERROR_TRANSACTION_COLLISION				0x23
#define LMP_PDU_NOT_ALLOWED							0x24
#define ENCRYPTION_MODE_NOT_ACCEPTABLE				0x25
#define LINK_KEY_CAN_NOT_BE_CHANGED					0x26
#define REQUEST_QoS_NOT_SUPPORTED					0x27
#define INSTANT_PASSED								0x28
#define PAIRING_UNIT_KEY_NOT_SUPPORTED				0x29
#define DIFFERENT_TRANSACTION_COLLISION				0x2A
#define QoS_UNACCEPTABLE_PARAM						0x2C
#define QoS_REJECTED								0x2D
#define CHANNEL_CLASSIFICATION_NOT_SUPPORTED		0x2E
#define INSUFFICIENT_SECURITY						0x2F
#define PARAMETER_OUT_OF_MANDATORY_RANGE			0x30
#define ROLE_SWITCH_PENDING							0x32
#define RESERVED_SLOT_VIOLATION						0x34
#define ROLE_SWITCH_FAILED							0x35
#define EXTENDED_INQUIRY_RESPONSE_TOO_LARGE			0x36
#define SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST		0x37
#define HOST_BUSY_PAIRING							0x38


#define NO_SCAN_ENABLED										0x00
#define	INQUIRY_SCAN_ENABLE_PAGE_SCAN_DISABLE				0x01
#define INQUIRY_SCAN_DISABLE_PAGE_SCAN_ENABLE				0x02
#define INQUIRY_PAGE_SCAN_ENABLE							0x03
#define	STD_SCAN											0x00
#define	INTERLACED_SCAN										0x01
#define	STD_INQUIRY_RESULT_FORMAT							0x00
#define	INQUIRY_RESULT_WITH_RSSI							0x01
#define	INQUIRY_RESULT_WITH_RSSI_EXTENDED_INQUIRY_RESULT	0x02
#define	VARIABLE_PIN_TYPE									0x00
#define	FIXED_PIN_TYPE										0x01
#define	MAINTAIN_CURRENT_POWER_STATE						0x00
#define	SUSPEND_PAGE_SCAN									0x01
#define	SUSPEND_INQUIRY_SCAN								0x02
#define	SUSPEND_PERIODIC_INQUIRIES							0x04
#define	DISABLE_ALL_LM_MODES								0x0000
#define	ENABLE_ROLE_SWITCH									0x0001
#define	ENABLE_HOLD_MODE									0x0002
#define	ENABLE_SNIFF_MODE									0x0004
#define	ENABLE_PARK_STATE									0x0008
#define	SYNCHRONOUS_FLOW_CONTROL_ENABLE						0x01
#define	SYNCHRONOUS_FLOW_CONTROL_DISABLE 					0x00
#define	ERRONEOUS_DATA_REPORTING_DISABLE 					0x00
#define ERRONEOUS_DATA_REPORTING_ENABLE						0x01


#endif
